version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  my-app:
    #image: amazoncorretto:11
    build:
        context: .
        dockerfile: DockerfileRodarAplicacaoJava

    #ports:
    #  - "8080:8080"
    #volumes:
    #  - ./app:/app
    #environment:
    #  - SPRING_PROFILES_ACTIVE=prod
    #command: java -jar app.jar

volumes:
  mongodb_data_container: