server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: rootpassword
      database: tech-parquimetro